FROM python:3.8
RUN pip install web3
RUN pip install jsonrpclib
COPY boba_community/fraud-detector/fraud-detector.py /
COPY /packages/contracts/artifacts/contracts/L1/rollup/StateCommitmentChain.sol/StateCommitmentChain.json /contracts/StateCommitmentChain.json
COPY /packages/contracts/artifacts/contracts/libraries/resolver/Lib_AddressManager.sol/Lib_AddressManager.json /contracts/Lib_AddressManager.json

CMD [ "python", "-u", "./fraud-detector.py" ]
