service: sls-boba-bobalink # NOTE: update this with your service name

provider:
  name: aws
  runtime: nodejs12.x
  stackName: sls-boba-bobalink
  stage: prod
  region: us-east-1
  role: ${file(env.yml):ROLE}

package:
  exclude:
    - .gitignore
    - node_modules
  individually: true

functions:
  bobalink_getQuote:
    handler: bobalink_getQuote.exportHandler
    memorySize: 10240 # optional, in MB, default is 1024
    timeout: 60 # optional, in seconds, default is 6
    vpc:
      securityGroupIds:
        - ${file(env.yml):SECURITY_GROUPS}
      subnetIds:
        - ${file(env.yml):SUBNET_ID_1}
        - ${file(env.yml):SUBNET_ID_2}
    events:
      - http:
          path: get.quote
          method: post
          cors: true
    layers:
      - ${file(env.yml):LAYERS}

