version: "3"

x-l1_rpc_dtl: &l1_rpc_dtl
  DATA_TRANSPORT_LAYER__L1_RPC_ENDPOINT: 'https://mainnet.gateway.tenderly.co'

x-l1_node_web3_url: &l1_node_web3_url
  L1_NODE_WEB3_URL: 'https://mainnet.gateway.tenderly.co'

services:
  verifier_dtl:
    image: omgx/data-transport-layer:rc1.0-surgery
    env_file:
      -  ../../ops/envs/dtl.env
    environment:
      <<: *l1_rpc_dtl
      DATA_TRANSPORT_LAYER__CONFIRMATIONS: 8
      DATA_TRANSPORT_LAYER__SYNC_FROM_L1: 'true'
      DATA_TRANSPORT_LAYER__SYNC_FROM_L2: 'false'
      DATA_TRANSPORT_LAYER__L2_CHAIN_ID: 288
      DATA_TRANSPORT_LAYER__ETH1_CTC_DEPLOYMENT_HEIGHT: 13011896
      DATA_TRANSPORT_LAYER__POLLING_INTERVAL: 10000
      DATA_TRANSPORT_LAYER__ADDRESS_MANAGER: '0x8376ac6C3f73a25Dd994E0b0669ca7ee0C02F089'
    volumes:
      - ./state-dumps/v1_mainnet/:/opt/optimism/packages/data-transport-layer/state-dumps/
    #  - ./<YOUR PERSISTED STORAGE>:/db/
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "10m"
    ports:
      - ${DTL_PORT:-7878}:7878
      - ${REGISTRY_PORT:-8080}:8081

  verifier_l2geth:
    depends_on:
      - verifier_dtl
    image: omgx/l2geth:rc1.0
    deploy:
      replicas: 1
    entrypoint: sh ./geth.sh
    env_file:
      - ../../ops/envs/geth.env
    #volumes:
    #  - ./<YOUR PERSISTED STORAGE>:/root/.ethereum/
    environment:
      ROLLUP_TIMESTAMP_REFRESH: 5s
      ROLLUP_STATE_DUMP_PATH: http://verifier_dtl:8081/state-dump.latest.json
      ROLLUP_CLIENT_HTTP: http://verifier_dtl:7878
      ROLLUP_BACKEND: 'l1'
      ROLLUP_VERIFIER_ENABLE: 'true'
      RETRIES: 60
      # no need to keep this secret, only used internally to sign blocks
      BLOCK_SIGNER_KEY: "6587ae678cf4fc9a33000cdbf9f35226b71dcc6a4684a31203241f9bcfd55d27"
      BLOCK_SIGNER_ADDRESS: "0x00000398232E2064F896018496b4b44b3D62751F"
      ROLLUP_POLL_INTERVAL_FLAG: "10s"
      ROLLUP_ENFORCE_FEES: 'true'
      DEV: true
      CHAIN_ID: 288
      NETWORK_ID: 288
      ETH1_L1_CROSS_DOMAIN_MESSENGER_ADDRESS: "0x6D4528d192dB72E282265D6092F4B872f9Dff69e"
      ROLLUP_ADDRESS_MANAGER_OWNER_ADDRESS: "0x1f2414D0af8741Bc822dBc2f88069c2b2907a840"
      ETH1_L1_STANDARD_BRIDGE_ADDRESS: "0xdc1664458d2f0B6090bEa60A8793A4E66c2F1c00"
      ETH1_L1_FEE_WALLET_ADDRESS: 0xbF159Ba5E5917551c70E377ADf21eD3736209fCE
      ROLLUP_GAS_PRICE_ORACLE_OWNER_ADDRESS: 0xd86D22c02E301BE7C35e3Ef20962f614cAf32B76
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "10m"
    ports:
      - ${VERIFIER_HTTP_PORT:-8547}:8545
      - ${VERIFIER_WS_PORT:-8548}:8546

  fraud-detector:
    depends_on:
     - verifier_dtl
     - verifier_l2geth
    image: bobanetwork/fraud-detector:${RELEASE_VERSION}
    deploy:
      replicas: 1
    environment:
      <<: *l1_node_web3_url
      L1_CONFIRMATIONS: 8
      L2_NODE_WEB3_URL: http://verifier_l2geth:8545 # There is no active Layer2 for V1_mainnet
      L2_CHECK_INTERVAL: 10
      VERIFIER_WEB3_URL: http://verifier_l2geth:8545
      ADDRESS_MANAGER_ADDRESS: '0x8376ac6C3f73a25Dd994E0b0669ca7ee0C02F089'
      L1_DEPLOYMENT_BLOCK: 13011896
      L2_START_BLOCK: 1
      SCC_NAME: 'OVM_StateCommitmentChain'
    #volumes:
    #  - ./<YOUR PERSISTED STORAGE>:/db/
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "10m"
    ports:
      - ${FRAUD_CHECKER_HTTP_PORT:-8555}:8555
