AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Resources:
  HelloKYC:
    Type: AWS::Lambda::Function
    Properties:
      Handler: kyc.lambda_handler
      Runtime: python3.9
      Events:
        HttpGet:
          Type: Api
          Properties:
            Path: '/'
            Method: get
