AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Resources:
  HelloTwitter:
    Type: AWS::Serverless::Function
    Properties:
      Handler: twitter.lambda_handler
      Runtime: python3.9
      Events:
        HttpGet:
          Type: Api
          Properties:
            Path: '/'
            Method: post
