FROM bobanetwork/data-transport-layer

COPY boba-node/docker/state-dump.latest.json /opt/optimism/packages/data-transport-layer/state-dumps/state-dump.latest.json

ENTRYPOINT ["node", "dist/src/services/run.js"]