AWSTemplateFormatVersion: "2010-09-09"
Description: "Enya Batch Submitter Deployment"

Parameters:
  EnvironmentName:
    Type: String
    Default: dev

  ServiceCount:
    Type: Number
    Default: 1

  ImageTag:
    Type: String
    Default: push2aws


  BatchSubmitterImage:
    Type: String
    Default: go-batch-submitter

  DockerPrefix:
    Type: String
    Default: bobanetwork

  LogsRetention:
    Type: Number
    Default: 7

  InfrastructureStackName:
    Description: Infrastructure stack to associate this stack with
    Type: String
    Default: infrastructure-coredev

Conditions:
  IsProduction:
    !Equals [!Ref EnvironmentName, "production"]

Resources:
  PrimaryAsymmetricKey:
    Type: AWS::KMS::Key
    Properties:
      Description: !Sub Primary key for ${AWS::StackName}
      KeySpec: ECC_SECG_P256K1
      KeyUsage: SIGN_VERIFY
      KeyPolicy:
        Version: 2012-10-17
        Id: !Ref AWS::StackName
        Statement:
          - Sid: Enable IAM User Permissions
            Effect: Allow
            Principal:
              AWS: !Sub arn:aws:iam::${AWS::AccountId}:root
            Action: kms:*
            Resource: "*"

  SecondaryAsymmetricKey:
    Type: AWS::KMS::Key
    Properties:
      Description: !Sub Secondary key for ${AWS::StackName}
      KeySpec: ECC_SECG_P256K1
      KeyUsage: SIGN_VERIFY
      KeyPolicy:
        Version: 2012-10-17
        Id: !Ref AWS::StackName
        Statement:
          - Sid: Enable IAM User Permissions
            Effect: Allow
            Principal:
              AWS: !Sub arn:aws:iam::${AWS::AccountId}:root
            Action: kms:*
            Resource: "*"

  TaskRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service: !Sub ecs-tasks.${AWS::URLSuffix}
            Action: sts:AssumeRole
      Policies:
        - PolicyName: AllowAccessToS3
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - "s3:GetObject"
                  - "s3:GetBucketLocation"
                Resource: !Sub
                    - "arn:aws:s3:::${S3BucketV2}/bath-submitter.env"
                    - S3BucketV2:
                        Fn::ImportValue: !Sub "${InfrastructureStackName}:S3BucketV2"
        - PolicyName: AllowAccessToKMS
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - kms:Sign
                  - kms:Verify
                  - kms:GetPublicKey
                Resource:
                  - !GetAtt PrimaryAsymmetricKey.Arn
                  - !GetAtt SecondaryAsymmetricKey.Arn

  TaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      ContainerDefinitions:
        - Image: !Sub "${DockerPrefix}/${BatchSubmitterImage}:${ImageTag}"
          Name: batch_submitter
          EnvironmentFiles:
            - Value: !Sub
              - "arn:aws:s3:::${S3BucketV2}/batch-submitter.env"
              - S3BucketV2:
                  Fn::ImportValue: !Sub "${InfrastructureStackName}:S3BucketV2"
              Type: "s3"
          Environment:
            - Name: URL
              Value: !Sub
                - "http://${EndpointAddress}:8081/addresses.json"
                - EndpointAddress:
                    Fn::ImportValue: !Sub "${InfrastructureStackName}:LoadBalancerInt:DNSName"
            - Name: L2_NODE_WEB3_URL
              Value: !Sub
                - "https://${EndpointAddress}"
                - EndpointAddress:
                    Fn::ImportValue: !Sub "${InfrastructureStackName}:DomainName"
            - Name: L2_ETH_RPC
              Value: !Sub
                - "https://${EndpointAddress}"
                - EndpointAddress:
                    Fn::ImportValue: !Sub "${InfrastructureStackName}:DomainName"
            - Name: DEPLOYER_HTTP
              Value: !Sub
                - "http://${EndpointAddress}:8081"
                - EndpointAddress:
                    Fn::ImportValue: !Sub "${InfrastructureStackName}:LoadBalancerInt:DNSName"
            - Name: PRIMARY_KMS_KEY
              Value: !GetAtt PrimaryAsymmetricKey.Arn
            - Name: SECONDARY_KMS_KEY
              Value: !GetAtt SecondaryAsymmetricKey.Arn
          DockerLabels:
            com.datadoghq.ad.check_names: '["batch_submitter"]'
            com.datadoghq.ad.init_configs: '[{}]'
            com.datadoghq.ad.logs: '[{"source": "batch_submitter", "service": "batch_submitter"}]'
          Essential: true
          Memory: "300"
          EntryPoint:
            # - "./batches.sh" # TS batch
            - "./batch-submitter.sh" # go batch
          LogConfiguration:
            LogDriver: json-file
            Options:
              max-file: "5"
              max-size: "10m"
      NetworkMode: bridge
      TaskRoleArn: !GetAtt TaskRole.Arn
      ExecutionRoleArn: "arn:aws:iam::942431445534:role/ecs-s3-rolw"
      Family: !Sub "BatchSubmitter-${EnvironmentName}"
  ECSService:
    Type: AWS::ECS::Service
    Properties:
      Cluster:
        Fn::ImportValue: !Sub "${InfrastructureStackName}:EcsCluster"
      DesiredCount: !Ref ServiceCount
      LaunchType: EC2
      SchedulingStrategy: REPLICA
      ServiceName: "batch-submitter"
      TaskDefinition: !Ref TaskDefinition
