[profile.default]
src = "contracts"
out = "out"
libs = ["node_modules", "lib"]
test = "test/unit"
solc = "0.8.16"
optimizer = true
optimizer_runs = 10_000
gas_reports = ['*']
remappings = [
  "@openzeppelin/contracts=node_modules/@openzeppelin/contracts"
]

[rpc_endpoints]
  local_boba = "http://127.0.0.1:8545"
  boba_goerli = "https://replica.goerli.boba.network"
  boba_mainnet = "https://boba-ethereum.gateway.tenderly.co/1clfZoq7qEGyF4SQvF8gvI"
  boba_bnbtestnet = "https://boba-bnb-testnet.gateway.tenderly.co/1clfZoq7qEGyF4SQvF8gvI"
  boba_bnbmainnet = "https://boba-bnb.gateway.tenderly.co/1clfZoq7qEGyF4SQvF8gvI"

# See more config options https://github.com/foundry-rs/foundry/tree/master/config
