version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "warm"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1cz0wzdvk89x9"
s3_prefix = "warm"
region = "eu-central-1"
capabilities = "CAPABILITY_IAM"
image_repositories = []
profile = "wavect"
confirm_changeset = true
