AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Resources:
  MainnetFaucetGetCaptcha:
    Type: AWS::Serverless::Function
    Properties:
      Handler: hc_getCAPTCHA.lambda_handler
      Runtime: python3.9
      Events:
        HttpGet:
          Type: Api
          Properties:
            Path: '/'
            Method: post
  MainnetFaucetVerifyCaptcha:
    Type: AWS::Serverless::Function
    Properties:
      Handler: hc_verifyCAPTCHA.lambda_handler
      Runtime: python3.9
      Events:
        HttpGet:
          Type: Api
          Properties:
            Path: '/'
            Method: post
