version: "3"

services:
  gas_oracle:
    depends_on:
      - l1_chain
      - l2geth
    image: bobanetwork/boba_gas-price-oracle:latest
    build:
      context: ..
      dockerfile: ./ops/docker/Dockerfile.boba_gas-price-oracle
    environment:
      ADDRESS_MANAGER_ADDRESS: "0x5FbDB2315678afecb367f032d93F642f64180aa3"
      L1_NODE_WEB3_URL: http://l1_chain:8545
      L2_NODE_WEB3_URL: http://l2geth:8545
      GAS_PRICE_ORACLE_ADDRESS: "0x420000000000000000000000000000000000000F"
      ADDRESS_MANAGER_ADDRESS: "0x5FbDB2315678afecb367f032d93F642f64180aa3"
      << : *gas-price-oracle_pk #same as the deployer
      << : *relayer_pk
      << : *fast-relayer_pk
      SEQUENCER_ADDRESS: "0x70997970c51812dc3a010c7d01b50e0d17dc79c8"
      PROPOSER_ADDRESS: "0x3c44cdddb6a900fa2b585dd299e03d12fa4293bc"
      GAS_PRICE_ORACLE_FLOOR_PRICE: 1
      GAS_PRICE_ORACLE_ROOF_PRICE: 5
      GAS_PRICE_ORACLE_MIN_PERCENT_CHANGE:
      POLLING_INTERVAL:
      RETRIES: 200

  monitor:
    depends_on:
     - l1_chain
     - l2geth
    image: bobanetwork/monitor:latest
    build:
      context: ..
      dockerfile: ./ops/docker/Dockerfile.monitor
    deploy:
      replicas: 0
