version: "3"

# Account #0
x-deployer_pk: &deployer_pk
  DEPLOYER_PRIVATE_KEY: '0xac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80'

# Account #6 - bobalink test
x-bobalink_pk: &bobalink_pk
  BOBALINK_REPORTER_KEY: '0x92db14e403b83dfe3df233f83dfa3a0d7096f21ca9b0d6d6b8d88b2b4ec1564e'

# Account #19
x-gas-price-oracle_pk: &gas-price-oracle_pk
  GAS_PRICE_ORACLE_OWNER_PRIVATE_KEY: '0xdf57089febbacf7ba0bc227dafbffa9fc08a93fdc68e1e42411a14efcf23656e'

# Account #8
x-relayer_pk: &relayer_pk
  RELAYER_PRIVATE_KEY: '0xdbda1821b80551c9d65939329250298aa3472ba22feea921c0cf5d620ea67b97'

# Account #18
x-fast-relayer_pk: &fast-relayer_pk
  FAST_RELAYER_PRIVATE_KEY: '0xde9be858da4a475276426320d5e9262ecfc3ba460bfac56360bfa6c4c28b4ee0'


services:
  gas_oracle:
    depends_on:
      - l1_chain
      - l2geth
    image: bobanetwork/boba_gas-price-oracle:latest
    build:
      context: ..
      dockerfile: ./ops/docker/Dockerfile.packages
      target: gas_oracle
    environment:
      ADDRESS_MANAGER_ADDRESS: "0x5FbDB2315678afecb367f032d93F642f64180aa3"
      L1_NODE_WEB3_URL: http://l1_chain:8545
      L2_NODE_WEB3_URL: http://l2geth:8545
      GAS_PRICE_ORACLE_ADDRESS: "0x420000000000000000000000000000000000000F"
      ADDRESS_MANAGER_ADDRESS: "0x5FbDB2315678afecb367f032d93F642f64180aa3"
      << : *gas-price-oracle_pk #same as the deployer
      << : *relayer_pk
      << : *fast-relayer_pk
      SEQUENCER_ADDRESS: "0x70997970c51812dc3a010c7d01b50e0d17dc79c8"
      PROPOSER_ADDRESS: "0x3c44cdddb6a900fa2b585dd299e03d12fa4293bc"
      GAS_PRICE_ORACLE_FLOOR_PRICE: 1
      GAS_PRICE_ORACLE_ROOF_PRICE: 5
      GAS_PRICE_ORACLE_MIN_PERCENT_CHANGE:
      POLLING_INTERVAL:
      RETRIES: 200
    deploy:
      replicas: 0

  monitor:
    depends_on:
     - l1_chain
     - l2geth
    image: bobanetwork/monitor:latest
    build:
      context: ..
      dockerfile: ./ops/docker/Dockerfile.monitor
    deploy:
      replicas: 0

  teleportation:
    depends_on:
     - l2geth
    image: bobanetwork/teleportation:latest
    build:
      context: ..
      dockerfile: ./ops/docker/Dockerfile.packages
      target: teleportation
    deploy:
      replicas: 0

  bobalink:
    depends_on:
     - l2geth
    image: bobanetwork/bobalink:latest
    build:
      context: ..
      dockerfile: ./ops/docker/Dockerfile.packages
      target: bobalink
    environment:
      L1_NODE_WEB3_URL: http://l2geth:8545
      L2_NODE_WEB3_URL: http://l2geth:8545
      ADDRESS_MANAGER_ADDRESS: "0x5FbDB2315678afecb367f032d93F642f64180aa3"
      << : *bobalink_pk
      URL: http://dtl:8081/addresses.json
      BOBA_URL: http://dtl:8081/boba-addr.json
      POLLING_INTERVAL: 1000

  # deploys account abstraction contracts and serves contract addresses
  aa_deployer:
    depends_on:
      - l1_chain
      - dtl
      - l2geth
      - boba_deployer
    image: bobanetwork/aa_deployer:latest
    build:
      context: ..
      dockerfile: ./ops/docker/Dockerfile.packages
      target: aa_deployer
    environment:
      L1_NODE_WEB3_URL: http://l1_chain:8545
      L2_NODE_WEB3_URL: http://l2geth:8545
      ADDRESS_MANAGER_ADDRESS: "0x5FbDB2315678afecb367f032d93F642f64180aa3"
      URL: http://dtl:8081/addresses.json
      BOBA_URL: http://dtl:8081/boba-addr.json
      # DO NOT use in production
      << : *deployer_pk
      RETRIES: 200
      DTL_REGISTRY_URL: http://dtl:8081/aa-addr.json
      # skip compilation when run in docker-compose, since the contracts
      # were already compiled in the builder step
      NO_COMPILE: 1

  proxyd:
    image: bobanetwork/proxyd:latest
    build:
      context: ../go/
      dockerfile: ./proxyd/Dockerfile
    deploy:
      replicas: 0
