name: Publish AA-Bundler to NPM
on:
  #todo release:
  #  types: [created]
  push:
    branches:
      - wsdt/bundler-2-ci-pipeline #todo

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'
          registry-url: 'https://registry.npmjs.org'
      - name: Install dependencies and build 🔧
        run: yarn install --frozen-lockfile --legacy-peer-deps && yarn run build
      - name: Publish package on NPM 📦
        working-directory: ./packages/boba/bundler_sdk
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_BOBA_FOUNDATION }}
