name: Publish AA-Bundler to NPM
on:
  #todo release:
  #  types: [created]
  on:
    push:
      branches:
        - wsdt/bundler-2-ci-pipeline #todo

defaults:
  run:
    working-directory: ./packages/boba/bundler_sdk

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '14.x'
          registry-url: 'https://registry.npmjs.org'
      - name: Install dependencies and build 🔧
        run: npm ci && npm run build
      - name: Publish package on NPM 📦
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_BOBA_FOUNDATION }}
