name: End to end test(Headful)
permissions: read-all

on:
  push:
    paths:
      - 'packages/boba/gateway/**/*'
      - '.github/workflows/end2end-test.yml'

jobs:
  End-to-End-Test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: 16.16.0
          cache: 'yarn'
      - name: Cache node modules
        id: cache-node-modules
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.os }}-yarn-${{ hashFiles('yarn.lock') }}
      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests
      - name: Install dependencies
        run: yarn; yarn build

      - uses: actions/cache/save@v3
        if: ${{steps.cache-node-modules.outputs.cache-hit != 'true'}}
        with:
          path: node_modules
          key: ${{ runner.os }}-yarn-${{ hashFiles('yarn.lock') }}
      - name: Install linux deps
        run: |
          sudo apt-get install --no-install-recommends -y \
          fluxbox \
          xvfb
      - name: Run end to end tests
        working-directory: ./packages/boba/gateway
        run: |
          Xvfb :0 -screen 0 1024x768x24 -listen tcp -ac &
          fluxbox & yarn test:integration
        env:
          REACT_APP_POLL_INTERVAL: 15000
          SKIP_PREFLIGHT_CHECK: true
          REACT_APP_WALLET_VERSION: 0.7.3
          REACT_APP_ENV: dev
          REACT_APP_STATUS: normal
          REACT_APP_SPEED_CHECK: ${{ secrets.REACT_APP_SPEED_CHECK }}
          REACT_APP_DISABLE_VE_DAO: 1
          REACT_APP_INFURA_ID: ${{ secrets.E2E_TEST_INFURA_ID }}
          CYPRESS_REMOTE_DEBUGGING_PORT: 9222
          NETWORK_NAME: 'goerli'
          SECRET_WORDS: ${{secrets.E2E_TEST_WALLET_SECRET_WORDS}}
          CYPRESS_TEST_HASH: ${{secrets.E2E_TEST_SAMPLE_HASH }}
          DISPLAY: :0.0
      - name: Upload videos
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: Test footage
          path: |
            ./packages/boba/gateway/cypress/videos/
            ./packages/boba/gateway/cypress/screenshots/
        continue-on-error: true
