name: Label Reviews
on:
  pull_request_review:

jobs:
  require-reviewers:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v3
        with:
          ref: develop

      # - name: Require-reviewers
      #   uses: travelperk/label-requires-reviews-action@v0.1
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN}}