name: 'Submodules Sync'

on:
  push:
  # Allows you to run this workflow manually from the Actions tab or through HTTP API
  workflow_dispatch:

jobs:
  sync:
    name: 'Submodules Sync'
    runs-on: ubuntu-latest

    # Use the Bash shell regardless whether the GitHub Actions runner is ubuntu-latest, macos-latest, or windows-latest
    defaults:
      run:
        shell: bash

    steps:
    # Checkout the repository to the GitHub Actions runner
    - name: Checkout
      uses: actions/checkout@v3
      with:
        token: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}
        submodules: true

    # Update references
    - name: Git Submodule Update
      run: |
        # If we want to update all, just commented bc. we already have a sync for tests
        cd bedrock/erigon
        git checkout devel
        git config --global user.name 'Github bot'
        git config --global user.email '<>'
        git pull origin devel
        git pull --tags
        cd ../..
        git add .
        git commit -m "Updated Erigon submodule" || echo "Nothing to commit"
        git push || echo "Nothing to push"
        
    - name: Reference-Optimistic-Geth Submodule Update
      run: |
        # If we want to update all, just commented bc. we already have a sync for tests
        cd bedrock/reference-optimistic-geth
        git checkout optimism-prototype
        git config --global user.name 'Github bot'
        git config --global user.email '<>'
        git pull origin optimism-prototype
        git pull --tags
        cd ../..
        git add .
        git commit -m "Updated Reference-Optimistic-Geth submodule" || echo "Nothing to commit"
        git push || echo "Nothing to push"
      # git pull --recurse-submodules
      # git submodule update --remote --recursive
