name: Git version tags.

on:
  pull_request:

jobs:
  prepare-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Get the version
        id: tag
        run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}
      - name: Print current tag
        run: echo ${{ steps.tag.outputs.VERSION }}
