FROM node:14-alpine

RUN apk add --no-cache git

WORKDIR /

COPY *.json yarn.lock ./
COPY patches ./patches

COPY ops_boba ./ops_boba
COPY packages/core-utils ./packages/core-utils
COPY packages/common-ts ./packages/common-ts
COPY packages/boba/contracts ./packages/boba/contracts
COPY packages/contracts ./packages/contracts
COPY packages/boba/turing ./packages/boba/turing

RUN yarn install && yarn build

WORKDIR /ops_boba/monitor

ENTRYPOINT yarn start
