version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "twitter-turing-bobabase"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-kwm4pw4xqxpt"
s3_prefix = "twitter-turing-bobabase"
region = "us-east-1"
profile = "boba"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
